services:
  - type: web
    name: n8n-telegram-bot-1
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /healthz
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        sync: false
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
